name: Discord Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Discord Notification
        uses: Ilshidur/action-discord@master
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
          message: |
            New commit by ${{ github.actor }} on `${{ github.repository }}`
            https://github.com/${{ github.repository }}/commit/${{ github.sha }}
